# https://dart.dev/tools/pub/pubspec
#  dart pub get
name: start_dart
description:
version: 1.0.0
homepage: https://github.com/ikuokuo/start-dart
documentation:

environment:
  sdk: '>=3.0.0'
  # sdk: '>=2.19.6 <3.0.0'

dependencies:
  ffi: ^2.0.2
  path: ^1.8.3

dev_dependencies:
  lints: ^2.1.1
